--INSERTAR DATOS DUPLICADOS
CREATE TABLE ftorren.C_COL (
ID_C_COL INT identity,
FEC_PROC DECIMAL(15,0), 
ANO_MES	DECIMAL(15,0), 
EJE	VARCHAR(50),
PLAT VARCHAR(50),
REG	VARCHAR(50),
TIPO_OPE VARCHAR(50),
BCA	VARCHAR(50),
SDO_M$ DECIMAL(15,0), 
SDO_PROM_M$ DECIMAL(15,0), 
VAR_DIA_SDO_M$ DECIMAL(15,0), 
VAR_MES_SDO_M$ DECIMAL(15,0), 
VAR_DIA_SDO_PROM_M$ DECIMAL(15,0), 
VAR_MES_SDO_PROM_M$ DECIMAL(15,0)
)

CREATE UNIQUE
INDEX ID_C_COL
ON  FTORREN.C_COL (ID_C_COL)
WITH ALLOW_DUP_ROW;