--INSERTAR DATOS DUPLICADOS
CREATE TABLE ftorren.C_COL (
ID_C_COL INT identity,
)
CREATE UNIQUE
INDEX ID_C_COL
ON  FTORREN.C_COL (ID_C_COL)
WITH ALLOW_DUP_ROW;



--BUSCAR COSAS RARAS EN LOS CAMPOS
WHERE RUT NOT LIKE '%[0-9]%';

WHERE RUT NOT LIKE '%[A-Z]%';