DROP TABLE ftorren.FACT_TABLE;

CREATE TABLE ftorren.FACT_TABLE (
			ID_FACT_TABLE INT identity,
			ID_DATE_TABLE INT,
			FEC_PROC INT,
			ANO_MES INT,
			ANO INT,
			TRIMESTRE INT,
			REGION VARCHAR(50),
			PLATAFORMA VARCHAR(50),
			EJECUTIVO VARCHAR(50)
)
CREATE UNIQUE
INDEX IDX_FACT_TABLE
ON  ftorren.FACT_TABLE (FEC_PROC,ANO_MES,ANO,TRIMESTRE,REGION,PLATAFORMA,EJECUTIVO)
WITH ALLOW_DUP_ROW;

CREATE INDEX IDX_1_FT ON  ftorren.FACT_TABLE (FEC_PROC,REGION,PLATAFORMA,EJECUTIVO);


INSERT INTO ftorren.FACT_TABLE(
ID_DATE_TABLE,
FEC_PROC,
ANO_MES,
ANO,
TRIMESTRE,
REGION,
PLATAFORMA,
EJECUTIVO
)
SELECT 
B.ID_DATE_TABLE,
A.FEC_PROC,
A.ANO_MES,
A.ANO,
A.TRIMESTRE,
A.REGION,
A.PLATAFORMA,
A.EJECUTIVO
FROM
(SELECT
DISTINCT
FEC_PROC,
ANO_MES,
ANO_MES/100 AS ANO,
QUARTER(CONVERT(DATETIME, CONVERT(CHAR(8), (FEC_PROC)))) AS TRIMESTRE,
TRIM(REG_CLI_DESC) AS REGION,
CASE
	WHEN TRIM(PLT_CLI_DESC)= 'CBUTTO' AND TRIM(PLT_CLI_DESC)= 'PLATAFORMA 1' THEN 'PLATAFORMA CENTRAL'
	WHEN TRIM(PLT_CLI_DESC)= 'RFREYMA' AND TRIM(PLT_CLI_DESC)= 'PLATAFORMA CENTRAL' THEN 'PLATAFORMA 10'
ELSE TRIM(PLT_CLI_DESC)
END PLATAFORMA,
CASE
	WHEN TRIM(EJE_CLI) = '' THEN 'SIN_EJE'
ELSE TRIM(EJE_CLI) 
END AS EJECUTIVO
FROM SGC.STOCK_VAR_DIA
WHERE FEC_PROC > CAST(DATEFORMAT(DATEADD(MONTH,-13,NOW()),'YYYYMMDD') AS INT)
AND TRIM(bca) IN('EM','EMQ')
AND rut <> '76804710'
AND REGION <> ''
AND PLATAFORMA <> '') A
LEFT JOIN FTORREN.DATE_TABLE B
ON A.FEC_PROC = B.FCH_INT


SELECT * FROM ftorren.FACT_TABLE
