--SEGUNDA CARGA
DROP TABLE ftorren.C_COL;

CREATE TABLE ftorren.C_COL (
ID_C_COL INT identity,
ID_PERIOD INT,
FEC_PROC INT,
ANO_MES INT,
TRIMESTRE INT,
REGION VARCHAR(50),
PLATAFORMA VARCHAR(50),
EJECUTIVO VARCHAR(50),
SDO_M$ DECIMAL(30,0),
SDO_PROM_M$ DECIMAL(30,0),
VAR_DIA_SDO_M$ DECIMAL(30,0),
VAR_MES_SDO_M$ DECIMAL(30,0),
VAR_DIA_SDO_PROM_M$ DECIMAL(30,0),
VAR_MES_SDO_PROM_M$ DECIMAL(30,0)
)
CREATE UNIQUE
INDEX IDX_C_COL
ON  FTORREN.C_COL (ID_C_COL,ID_PERIOD)
WITH ALLOW_DUP_ROW;

INSERT INTO ftorren.C_COL(
ID_PERIOD,
FEC_PROC,
ANO_MES,
TRIMESTRE,
REGION,
PLATAFORMA,
EJECUTIVO,
SDO_M$,
SDO_PROM_M$,
VAR_DIA_SDO_M$,
VAR_MES_SDO_M$,
VAR_DIA_SDO_PROM_M$,
VAR_MES_SDO_PROM_M$
)
SELECT
FP.ID_PERIOD,
SVD.FEC_PROC,
SVD.ANO_MES,
(convert(integer,right(left(convert(varchar(8),svd.ano_mes),6),2))-1)/3+1 as TRIMESTRE,
SVD.REGION,
SVD.PLATAFORMA,
SVD.EJECUTIVO,
SUM(SVD.SDO_OPE)/ 1000 AS SDO_M$,
SUM(SVD.SDO_PROM_ACUM)/ 1000 AS SDO_PROM_M$,
SUM(SVD.VAR_SDO_DIA_ANT )/ 1000 AS VAR_DIA_SDO_M$,
SUM(SVD.VAR_SDO_MES_ANT )/ 1000 AS VAR_MES_SDO_M$,
SUM(SVD.VAR_SDO_PROM_DIA_ANT )/ 1000 AS VAR_DIA_SDO_PROM_M$,
SUM(SVD.VAR_SDO_PROM_MES_ANT )/ 1000 AS VAR_MES_SDO_PROM_M$
FROM ftorren.STOCK_VAR_DIA SVD
LEFT JOIN ftorren.FACT_PERIOD FP
ON SVD.ANO_MES = FP.ANO_MES
AND SVD.REGION = FP.REGION
AND SVD.PLATAFORMA = FP.PLATAFORMA
AND SVD.EJECUTIVO = FP.EJECUTIVO
GROUP BY FP.ID_PERIOD,SVD.FEC_PROC,SVD.ANO_MES, SVD.REGION, SVD.PLATAFORMA, SVD.EJECUTIVO



