DROP TABLE ftorren.C_PPTO;

CREATE TABLE ftorren.C_PPTO (
ID_C_PPTO INT identity,
GRUPO4 VARCHAR(15),
GRUPO4_DESC VARCHAR(15),
ANO_MES DECIMAL(15,0), 
BCA VARCHAR(15),
OFI VARCHAR(15),
TIPO VARCHAR(15),
EJE VARCHAR(15),
PPTO DECIMAL(15,0),
GRUPO6_DESC VARCHAR(50),
GRUPO5_DESC VARCHAR(50),
LINEA_GRUPO3_DESC VARCHAR(50),
TRIMESTRE DECIMAL(15,0)
)
CREATE UNIQUE
INDEX ID_C_PPTO
ON  FTORREN.C_PPTO (ID_C_PPTO)
WITH IGNORE_DUP_ROW;

INSERT INTO ftorren.C_PPTO(
GRUPO4,
GRUPO4_DESC,
ANO_MES,
BCA,
OFI,
TIPO,
EJE,
PPTO,
GRUPO6_DESC,
GRUPO5_DESC,
LINEA_GRUPO3_DESC,
TRIMESTRE
)
SELECT 
TRIM(AL2.GRUPO4) AS GRUPO4, 
TRIM(AL2.DESC_GRUPO4) AS GRUPO4_DESC, 
AL1.ANO_MES, 
AL1.BCA, 
AL1.OFI, 
AL1.TIPO, 
CASE WHEN TRIM(AL1.EJE)='SINEJE' THEN 'SIN EJE' 
WHEN TRIM(AL1.EJE)='SIN_EJE' THEN 'SIN EJE' 
ELSE TRIM(AL1.EJE)
END AS EJE, 
AL1.PPTO, 
TRIM(AL2.DESC_GRUPO6) AS GRUPO6_DESC, 
TRIM(AL2.DESC_GRUPO5) AS GRUPO5_DESC, 
TRIM(AL3.LINEA_GRP3_DESC) AS LINEA_GRUPO3_DESC,
(CONVERT(INTEGER,RIGHT(LEFT(CONVERT(VARCHAR(8),AL1.ANO_MES),6),2))-1)/3+1 AS TRIMESTRE
FROM PPTO.ITE_EJE_TRS AL1
LEFT JOIN (SELECT OFICINA,GRUPO1,GRUPO3,GRUPO4,DESC_GRUPO4,DESC_GRUPO5,DESC_GRUPO6
FROM HISTORICA.BANCO WHERE TRIM(GRUPO1) = 'BCO_COM' 
AND TRIM(GRUPO3)='EM' GROUP BY OFICINA,GRUPO1,GRUPO3,GRUPO4,DESC_GRUPO4,DESC_GRUPO5,DESC_GRUPO6) AL2
ON AL1.OFI = AL2.OFICINA
LEFT JOIN (SELECT LINEA,LINEA_GRP1,LINEA_GRP3_DESC,LINEA_GRP4_DESC FROM DBA.LINEAS
WHERE TRIM(LINEA_GRP1) IN ('69U', 'CMS_399') 
AND TRIM(LINEA_GRP3_DESC) IN ('COLOCACIONES TOTALES', 'COMISIONES DE SERVICIOS', 'DEPOSITOS VISTAS NETOS') 
AND TRIM(LINEA_GRP4_DESC) IN ('CARTERAS VENCIDAS', 'COMISIONES POR SERVICIOS ESPECIALES', 'CONTINGENTES ACTIVOS', 'CREDITOS COMERCIALES', 'CREDITOS COMERCIO EXTERIOR', 'CREDITOS HIPOTECARIOS', 'CUENTA PRIMA', 'CUENTAS CORRIENTES', 'OTRAS VISTAS', 'OTROS CREDITOS', 'PRESTAMOS DE CONSUMO', 'SOBREGIRO Y LINEAS AVANCE', 'TARJETAS DE CREDITO')
GROUP BY LINEA,LINEA_GRP1,LINEA_GRP3_DESC,LINEA_GRP4_DESC) AL3
ON AL3.LINEA=AL1.LINEA
WHERE TRIM(AL1.BCA)='EM' 
AND TRIM(AL1.TIPO) IN ('CMS', 'PRM','MFI')
AND AL1.ANO_MES>=201606


--MESA
INSERT INTO ftorren.C_PPTO(
GRUPO4,
GRUPO4_DESC,
ANO_MES,
BCA,
OFI,
TIPO,
EJE,
PPTO,
GRUPO6_DESC,
GRUPO5_DESC,
LINEA_GRUPO3_DESC,
TRIMESTRE
)
SELECT 
LTRIM(RTRIM(AL1.uni_desc)) AS GRUPO4, 
ltrim(rtrim(AL1.reg_desc)) AS GRUPO4_DESC,
AL1.ano_mes AS ANO_MES, 
AL1.bca AS BCA,
'' AS OFI,
'MESA' AS TIPO, 
CASE WHEN upper(ltrim(rtrim(AL1.eje)))='SINEJE' then 'SIN EJE' 
when upper(ltrim(rtrim(AL1.eje)))='SIN_EJE' then 'SIN EJE' 
ELSE upper(ltrim(rtrim(AL1.eje))) 
END AS EJE, 
SUM (AL1.ppto_util) AS PPTO, 
ltrim(rtrim(AL1.plat_desc)) AS GRUPO6_DESC, 
AL1.prod_desc AS GRUPO5_DESC,
'UTILIDAD MESA' AS LINEA_GRUPO3_DESC,
(convert(integer,right(left(convert(varchar(8),AL1.ano_mes),6),2))-1)/3+1 as TRIMESTRE  
FROM MESA.msa_dis_prd_seg AL1
WHERE (LTRIM(RTRIM(AL1.uni_desc)) IN ('EMPRESAS') AND AL1.ano_mes>=201606)
GROUP BY AL1.ano_mes, AL1.bca, AL1.uni_desc, AL1.reg_desc, AL1.plat_desc, AL1.prod_desc, upper(ltrim(rtrim(AL1.eje)))