DROP TABLE ftorren.C_PPTO;

CREATE TABLE ftorren.C_PPTO (
ID_C_PPTO INT identity,
ID_PERIOD INT,
ANO_MES INT, 
REGION VARCHAR(15),
PLATAFORMA VARCHAR(50),
EJECUTIVO VARCHAR(15),
TIPO VARCHAR(15),
TRIMESTRE INT,
PPTO DECIMAL(15,0)
)
CREATE UNIQUE
INDEX ID_C_PPTO
ON  FTORREN.C_PPTO (ID_C_PPTO)
WITH IGNORE_DUP_ROW;

INSERT INTO ftorren.C_PPTO(
ID_PERIOD,
ANO_MES, 
REGION,
PLATAFORMA,
EJECUTIVO,
TIPO,
TRIMESTRE,
PPTO
)
SELECT 
FP.ID_PERIOD,
PP.ANO_MES,
PP.GRUPO4_DESC AS REGION,
PP.GRUPO6_DESC AS PLATAFORMA,
PP.EJE AS EJECUTIVO,
PP.TIPO,
PP.TRIMESTRE,
SUM(PP.PPTO)/1000 AS PPTO
FROM ftorren.TMP_C_PPTO PP
LEFT JOIN ftorren.FACT_PERIOD FP
ON PP.ANO_MES = FP.ANO_MES
AND PP.GRUPO4_DESC = FP.REGION
AND PP.GRUPO6_DESC = FP.PLATAFORMA
AND PP.EJE = FP.EJECUTIVO
WHERE PP.LINEA_GRUPO3_DESC = 'COLOCACIONES TOTALES'
GROUP BY FP.ID_PERIOD,PP.ANO_MES, PP.GRUPO4_DESC, PP.GRUPO6_DESC, PP.EJE, PP.TIPO,PP.TRIMESTRE

