DROP TABLE ftorren.FCH_RANGO;

CREATE TABLE ftorren.FCH_RANGO (
ID_FCH_PERIOD INT identity,
A_ANO INT,
A_MES INT,
A_DIA INT,
A_FECHA INT,
B_ANO INT,
B_MES INT,
B_DIA INT,
B_FECHA INT
)
CREATE UNIQUE
INDEX IDX_FCH_RANGO
ON  ftorren.FCH_RANGO (ID_FCH_PERIOD)
WITH ALLOW_DUP_ROW;

INSERT INTO ftorren.FCH_RANGO(
A_ANO,
A_MES,
A_DIA,
A_FECHA,
B_ANO,
B_MES,
B_DIA,
B_FECHA
)
SELECT
A.CAL_ANO AS A_ANO,
A.CAL_MES AS A_MES,
A.CAL_DIA AS A_DIA,
(A.CAL_ANO*10000+A.CAL_MES*100+A.CAL_DIA) AS A_FECHA,
B.CAL_ANO AS B_ANO,
B.CAL_MES AS B_MES,
B.CAL_DIA AS B_DIA,
(B.CAL_ANO*10000+B.CAL_MES*100+B.CAL_DIA) AS B_FECHA
FROM
(SELECT CAL_ANO,CAL_MES,MIN(CAL_DIA) AS CAL_DIA FROM HISTORICA.cal_dia
WHERE CAL_IND_DIA = 'H'
AND CAL_ANO > 2016
GROUP BY CAL_ANO,CAL_MES) A
LEFT JOIN (SELECT CAL_ANO,CAL_MES,MIN(CAL_DIA) AS CAL_DIA FROM HISTORICA.cal_dia
WHERE CAL_IND_DIA = 'H'
AND CAL_ANO > 2016
GROUP BY CAL_ANO,CAL_MES) B
ON A.CAL_ANO = B.CAL_ANO
WHERE A.CAL_MES = B.CAL_MES-1

-------------------------------------------------------

DROP TABLE ftorren.FCH_PERIOD;

CREATE TABLE ftorren.FCH_PERIOD (
ID INT identity,
ID_FCH_PERIOD INT,
FECHA INT,
CAL_ANO INT,
CAL_MES INT,
CAL_DIA INT,
CAL_TIP_DIA VARCHAR(15),
CAL_IND_DIA VARCHAR(15),
CAL_CTD_DIA INT
)
CREATE UNIQUE
INDEX IDX_FCH_PERIOD
ON  ftorren.FCH_PERIOD (ID)
WITH ALLOW_DUP_ROW;

INSERT INTO ftorren.FCH_PERIOD(
ID_FCH_PERIOD,
FECHA,
CAL_ANO,
CAL_MES,
CAL_DIA,
CAL_TIP_DIA,
CAL_IND_DIA,
CAL_CTD_DIA
)
SELECT
B.ID_FCH_PERIOD,
(A.CAL_ANO*10000+A.CAL_MES*100+A.CAL_DIA) FECHA,
A.CAL_ANO,
A.CAL_MES,
A.CAL_DIA,
A.CAL_TIP_DIA,
A.CAL_IND_DIA,
A.CAL_CTD_DIA
FROM HISTORICA.cal_dia A
LEFT JOIN ftorren.FCH_RANGO B
ON A.CAL_ANO = B.A_ANO
WHERE (A.CAL_ANO*10000+A.CAL_MES*100+A.CAL_DIA) BETWEEN B.A_FECHA AND B.B_FECHA-1
ORDER BY A.CAL_ANO, A.CAL_MES, A.CAL_DIA



SELECT * FROM ftorren.FCH_PERIOD