DROP TABLE FTORREN.DET_DIA_EMP_VTA;

CREATE TABLE FTORREN.DET_DIA_EMP_VTA (
ID_DDMV INT IDENTITY,
RUT VARCHAR(20),
FECHA INT,
ID_FCH_PERIOD INT,
MTO_PSO DECIMAL(30,6)
)
CREATE UNIQUE
INDEX IDX_ID_DDMV
ON  FTORREN.DET_DIA_EMP_VTA(ID_DDMV)
WITH ALLOW_DUP_ROW;

INSERT INTO FTORREN.DET_DIA_EMP_VTA(
RUT,
FECHA,
ID_FCH_PERIOD,
MTO_PSO
)
(SELECT 
SD.RUT,
FP.FECHA,
FP.ID_FCH_PERIOD,
SD.MTO_PSO
FROM SGC.DET_DIA_EMP_VTA SD
LEFT JOIN FTORREN.FCH_PERIOD FP
ON SD.FEC_PROC = FP.FECHA
WHERE SD.FEC_PROC > CAST(DATEFORMAT(DATEADD(MONTH,-7,NOW()),'YYYYMMDD') AS INT)
AND SD.PRD='SLV   ' 
AND SD.MTO_PSO != 0
GROUP BY SD.RUT,FP.FECHA,FP.ID_FCH_PERIOD,SD.MTO_PSO)