DROP TABLE FTORREN.SDO_PROM;

CREATE TABLE FTORREN.SDO_PROM (
ID_SDO_PROM INT IDENTITY,
MTO_PSO DECIMAL(30,6),  
RUT VARCHAR(20), 
DV VARCHAR(15), 
OFICINA VARCHAR(10), 
EJECUTIVO VARCHAR(20),
NOMBRE VARCHAR(40),
ID_FCH_PERIOD INT,
FECHA INT
)
CREATE UNIQUE
INDEX IDX_SDO_PROM
ON  FTORREN.SDO_PROM(ID_SDO_PROM)
WITH ALLOW_DUP_ROW;

INSERT INTO FTORREN.SDO_PROM(
MTO_PSO,
RUT,
DV,
OFICINA,
EJECUTIVO,
NOMBRE,
ID_FCH_PERIOD,
FECHA
)
SELECT
SUM(AL2.MTO_PSO*(1+AL2.CAL_CTD_DIA)) AS MTO_PSO,  
AL1.CLI_RUT AS RUT, 
AL1.CLI_DV AS DV, 
AL1.CLI_COD_OFI AS OFICINA, 
AL1.CLI_COD_EJE AS EJECUTIVO,
LTRIM(RTRIM(AL1.CLI_APE_PTN))+' '+LTRIM(RTRIM(AL1.CLI_APE_MTN))+' '+LTRIM(RTRIM(AL1.CLI_NOM)) AS NOMBRE,
AL2.ID_FCH_PERIOD,
AL2.FECHA
FROM CLIENTES.CLI_DIA AL1
INNER JOIN FTORREN.DET_DIA_EMP_VTA AL2
ON (AL1.CLI_RUT = AL2.RUT)
WHERE (AL1.CLI_FEC_FIN_REG='19000101'
AND AL1.CLI_IND=' ' 
AND AL1.CLI_EXT='   ' 
AND LTRIM(RTRIM(AL1.CLI_COD_CLS)) IN ('EM', 'EMQ'))
GROUP BY RUT, OFICINA, EJECUTIVO, DV, NOMBRE,AL2.ID_FCH_PERIOD,AL2.FECHA

