DROP TABLE FTORREN.C_DVN;

CREATE TABLE FTORREN.C_DVN (
ID_C_DVN INT IDENTITY,
EJECUTIVO VARCHAR(50),
RUT VARCHAR(50),
DV VARCHAR(10),
NOMBRE VARCHAR(100),
SDO_ACTUAL DECIMAL(30,6),
SDO_ANTERIOR DECIMAL(30,6),
VARIACION DECIMAL(30,6),
REGIONAL VARCHAR(50),
PLATAFORMA VARCHAR(50),
FECHA INT
)
CREATE UNIQUE
INDEX IDX_C_DVN
ON  FTORREN.C_DVN(ID_C_DVN)
WITH ALLOW_DUP_ROW;

INSERT INTO FTORREN.C_DVN(
EJECUTIVO,
RUT,
DV,
NOMBRE,
SDO_ACTUAL,
SDO_ANTERIOR,
VARIACION,
REGIONAL,
PLATAFORMA, 
FECHA
)
SELECT
A.EJECUTIVO,
A.RUT,
A.DV,
A.NOMBRE,
SUM(A.MTO_PSO)/1000 AS SDO_ACTUAL,
SUM(B.MTO_PSO)/1000 AS SDO_ANTERIOR,
(SUM(A.MTO_PSO)-SUM(B.MTO_PSO))/1000 AS VARIACION,
TRIM(C.DESC_GRUPO4) AS REGIONAL,
CASE 
WHEN TRIM(A.EJECUTIVO)='CBUTTO' 
AND TRIM(C.DESC_GRUPO6)='PLATAFORMA 1' THEN 'PLATAFORMA CENTRAL'
WHEN TRIM(A.EJECUTIVO)='RFREYMA' AND TRIM(C.DESC_GRUPO6)='PLATAFORMA CENTRAL' THEN 'PLATAFORMA 10' 
ELSE  TRIM(C.DESC_GRUPO6) END   AS PLATAFORMA, 
A.FECHA
FROM FTORREN.SDO_PROM A
LEFT JOIN FTORREN.SDO_PROM B
ON A.RUT = B.RUT
AND A.FECHA = B.FECHA-1
LEFT JOIN HISTORICA.BANCO C
ON A.OFICINA=C.OFICINA AND TRIM(C.GRUPO1)='BCO_COM' AND TRIM(C.GRUPO3)='EM' AND C.ANO_MES=(A.FECHA/100)
GROUP BY A.RUT, A.EJECUTIVO, PLATAFORMA, REGIONAL, A.DV, A.NOMBRE, A.FECHA

