/*
 *1. TARJETA DE CREDITO
 *2. CREDITO DE CONSUMO
 *3. HIPOTECARIO
 *4. SEGUROS DE VIDA
 *5. SEGUROS DE NO VIDA
 *6. CREDITO AUTOMOTRIZ
 **/

/*
 * EXCEPCIONES
 * 1. INVERSIONES
 * 2. CLIENTES UNICO PRODUCTO CREDITO CON MORA
 * 3. EXCLUIR PRODUCTOS DE MORA A CASTIGADO
 */

/*
SELECT
A.ANO_MES,
A.CLI,
A.BCA,
A.OFI,
A.LINEA,
B.DESC_LINEA,
B.LINEA_GRP4_DESC
FROM DBA.MARGEN A
LEFT JOIN DBA.LINEAS B
ON A.LINEA = B.LINEA
WHERE ANO_MES = 201706
AND CLI <> 'CLI_X'

SELECT * FROM DBA.LINEAS
WHERE LINEA_GRP4_DESC LIKE '%CREDITO%'

SELECT * FROM DBA.LINEAS
WHERE LINEA_GRP4 = 'SGR' --SOBREGIRO

SELECT * FROM DBA.LINEAS
WHERE LINEA_GRP4 = 'HIP' --HIPOTECARIOS

SELECT * FROM DBA.LINEAS
WHERE LINEA_GRP4 IN ('COM','OCR') --CREDITOS CONSUMO Y OTROS CREDITOS

SELECT * FROM DBA.LINEAS
WHERE LINEA_GRP4 = 'TDC' --TDC
*/

----------------------
DROP TABLE FTORREN.TOT_CLIENTE;

CREATE TABLE FTORREN.TOT_CLIENTE (
ID_TOT_CLIENTE INT IDENTITY,
ANO_MES INT,
CLI VARCHAR(20),
BCA VARCHAR(20),
OFI VARCHAR(20),
LINEA VARCHAR(20),
MARGEN_FINANCIERO DECIMAL(20,6)
)
CREATE UNIQUE
INDEX IDX_TOT_CLIENTE
ON  FTORREN.TOT_CLIENTE (ID_TOT_CLIENTE,CLI)
WITH ALLOW_DUP_ROW;

CREATE INDEX IDX_TC_BCA  ON  FTORREN.TOT_CLIENTE (BCA,OFI);

INSERT INTO FTORREN.TOT_CLIENTE(
ANO_MES,
CLI,
BCA,
OFI,
LINEA,
MARGEN_FINANCIERO
)
SELECT
A.ANO_MES,
TRIM(A.CLI) CLI,
A.BCA,
A.OFI,
A.LINEA,
SUM(A.MARGEN_FINANCIERO) AS MARGEN_FINANCIERO
FROM DBA.MARGEN A
WHERE ANO_MES = 201606
OR ANO_MES = 201706
AND CLI <> 'CLI_X'
GROUP BY A.ANO_MES,A.CLI,A.BCA,A.OFI,A.LINEA


DROP TABLE FTORREN.DBA_LINEA;

CREATE TABLE FTORREN.DBA_LINEA (
ID_DBA_LINEA INT IDENTITY,
LINEA_GRP4 VARCHAR(25),
LINEA VARCHAR(25),
DESC_LINEA VARCHAR(45)
)
CREATE UNIQUE
INDEX IDX_DBA_LINEA
ON  FTORREN.DBA_LINEA (ID_DBA_LINEA,LINEA)
WITH ALLOW_DUP_ROW;

INSERT INTO FTORREN.DBA_LINEA(
LINEA_GRP4,
LINEA,
DESC_LINEA
)
SELECT
LINEA_GRP4,
LINEA,
DESC_LINEA
FROM DBA.LINEAS
WHERE LINEA_GRP4 NOT LIKE 'CMS%'


DROP TABLE FTORREN.DBA_CLI_AWK;

CREATE TABLE FTORREN.DBA_CLI_AWK (
ID_DBA_CLI_AWK INT IDENTITY,
ANO_MES INT,
CLIENTE VARCHAR(20),
RUT INT
)
CREATE UNIQUE
INDEX IDX_DBA_CLI_AWK
ON  FTORREN.DBA_CLI_AWK (ID_DBA_CLI_AWK,CLIENTE)
WITH ALLOW_DUP_ROW;

INSERT INTO FTORREN.DBA_CLI_AWK(
ANO_MES,
CLIENTE,
RUT
)
SELECT
ANO_MES,
TRIM(CLIENTE) AS CLIENTE,
RUT
FROM DBA.CLI_AWK
WHERE IND_RUT = '' AND EXT_RUT = ''
AND CLIENTE <> 'CLI_X'
AND (ANO_MES = 201606
OR ANO_MES = 201706)


DROP TABLE FTORREN.DESC_CLIENTE;

CREATE TABLE FTORREN.DESC_CLIENTE (
ID_DESC_CLIENTE INT IDENTITY,
ANO_MES INT,
CLI VARCHAR(20),
BCA VARCHAR(20),
OFI VARCHAR(20),
LINEA_GRP4 VARCHAR(20),
LINEA VARCHAR(20),
MARGEN_FINANCIERO DECIMAL(20,6),
DESC_LINEA VARCHAR(20),
RUT INT,
DESC_BANCA VARCHAR(20)
)
CREATE UNIQUE
INDEX IDX_DESC_CLIENTE
ON  FTORREN.DESC_CLIENTE (ID_DESC_CLIENTE,CLI)
WITH ALLOW_DUP_ROW;

CREATE INDEX IDX_DC_LINEA  ON  FTORREN.DESC_CLIENTE (LINEA);

INSERT INTO FTORREN.DESC_CLIENTE(
ANO_MES,
CLI,
BCA,
OFI,
LINEA_GRP4,
LINEA,
MARGEN_FINANCIERO,
DESC_LINEA,
RUT,
DESC_BANCA
)
SELECT
A.ANO_MES,
A.CLI,
A.BCA,
A.OFI,
B.LINEA_GRP4,
A.LINEA,
A.MARGEN_FINANCIERO,
B.DESC_LINEA,
C.RUT,
D.DESC_BANCA
FROM FTORREN.TOT_CLIENTE A
LEFT JOIN FTORREN.DBA_LINEA B ON A.LINEA = B.LINEA
LEFT JOIN FTORREN.DBA_CLI_AWK C ON TRIM(A.CLI) = TRIM(C.CLIENTE) AND A.ANO_MES = C.ANO_MES
LEFT JOIN DBA.ESTRUCTURA D ON A.BCA = D.BCA AND A.OFI = D.OFI
--WHERE A.ANO_MES = 201606



--

------------------------------------------------

SELECT DISTINCT DESC_BANCA FROM FTORREN.DESC_CLIENTE

SELECT RUT, DESC_BANCA, COUNT(*) FROM FTORREN.DESC_CLIENTE
WHERE LINEA_GRP4  = 'CCT'
AND ANO_MES = 201706
GROUP BY RUT, DESC_BANCA

SELECT COUNT (DISTINCT RUT)FROM FTORREN.DESC_CLIENTE
WHERE LINEA_GRP4  = 'CCT'
AND DESC_BANCA IN ('PREFERENCIAL','TBANC','PERSONAS')
AND ANO_MES = 201706


SELECT COUNT (DISTINCT RUT)FROM FTORREN.DESC_CLIENTE
WHERE LINEA_GRP4  = 'CCT'
AND ANO_MES = 201706


SELECT * FROM FTORREN.DESC_CLIENTE

--UNIVERSO DE CLIENTES
SELECT COUNT (DISTINCT RUT)FROM FTORREN.DESC_CLIENTE
WHERE DESC_BANCA IN ('PREFERENCIAL','TBANC','PERSONAS')
AND LINEA_GRP4 IN ('DAP','CCT','HIP','TDC')
AND ANO_MES = 201606


SELECT * FROM SGC.STOCK_CLIENTE

SELECT * FROM GESFOR.DVN_STOCK_CCT
