--UTILIDAD CLIENTES FILIAL Y BCI
DROP TABLE ftorren.UTILIDAD_CLIENTE;

CREATE TABLE ftorren.UTILIDAD_CLIENTE (
ID_UTILIDAD_CLIENTE INT IDENTITY,
ID_PERIODO INT,
RUT INT,
EJECUTIVO_CLIENTE VARCHAR(50),
MARGEN_BRUTO DECIMAL(30,6),
COSTO_TOTAL DECIMAL(30,6),
GASTO_RIESGO DECIMAL(30,6),
MARGEN_FINANCIERO DECIMAL(30,6),
POND_TASA_IMPUESTO DECIMAL(30,6),
LINEA_GRP4 VARCHAR(10),
LINEA VARCHAR(10),
DESC_LINEA VARCHAR(100),
UTILIDAD_CLIENTE DECIMAL(30,6)
)
CREATE UNIQUE
INDEX IDX_UTILIDAD_CLIENTE
ON  FTORREN.UTILIDAD_CLIENTE (ID_UTILIDAD_CLIENTE,RUT)
WITH ALLOW_DUP_ROW;

INSERT INTO ftorren.UTILIDAD_CLIENTE(
ID_PERIODO,
RUT,
EJECUTIVO_CLIENTE,
MARGEN_BRUTO,
COSTO_TOTAL,
GASTO_RIESGO,
MARGEN_FINANCIERO,
POND_TASA_IMPUESTO,
LINEA_GRP4,
LINEA,
DESC_LINEA,
UTILIDAD_CLIENTE
)
SELECT
A.ID_PERIODO,
A.RUT,
A.EJECUTIVO_CLIENTE,
A.MARGEN_BRUTO,
A.COSTO_TOTAL,
A.GASTO_RIESGO,
A.MARGEN_FINANCIERO,
A.POND_TASA_IMPUESTO,
B.LINEA_GRP4,
B.LINEA,
B.DESC_LINEA,
A.MARGEN_FINANCIERO*A.POND_TASA_IMPUESTO AS UTILIDAD_CLIENTE
FROM QWRTB.QWR_FT_RENTABILIDAD_CLIENTE A
LEFT JOIN DBA.LINEAS B ON TRIM(A.COD_PRODUCTO) = TRIM(B.LINEA) AND B.LINEA_GRP4 IN ('SGR','HIP','COM','OCR','TDC')
WHERE (A.ID_PERIODO = 201606
OR A.ID_PERIODO = 201706)
AND A.RUT > 0



SELECT 
ID_PERIODO AS ANO_MES,
RUT,
'X' AS IND_UTILIDAD
FROM FTORREN.UTILIDAD_CLIENTE
WHERE UTILIDAD_CLIENTE <> 0
AND LINEA IS NOT NULL
GROUP BY ANO_MES,RUT


DROP TABLE FTORREN.RESUMEN_UTILIDAD;

CREATE TABLE FTORREN.RESUMEN_UTILIDAD (
ID_RESUMEN_UTILIDAD INT IDENTITY,
ANO_MES INT,
RUT INT,
IND_UTILIDAD VARCHAR(10)
)
CREATE UNIQUE
INDEX IDX_RESUMEN_UTILIDAD
ON  FTORREN.RESUMEN_UTILIDAD (ID_RESUMEN_UTILIDAD,RUT)
WITH ALLOW_DUP_ROW;

CREATE INDEX IDX_AM_RUT_RU ON  FTORREN.RESUMEN_UTILIDAD (ANO_MES,RUT);

INSERT INTO FTORREN.RESUMEN_UTILIDAD(
ANO_MES,
RUT,
IND_UTILIDAD
)
SELECT 
ID_PERIODO AS ANO_MES,
RUT,
'X' AS IND_UTILIDAD
FROM FTORREN.UTILIDAD_CLIENTE
WHERE UTILIDAD_CLIENTE <> 0
AND LINEA IS NOT NULL
GROUP BY ANO_MES,RUT



--SELECT * FROM FTORREN.RESUMEN_UTILIDAD


/*SELECT * FROM LRIOSEC.CLIENTES_ACTIVOS_POR_SALDO*/
