/*
SELECT * FROM FTORREN.RESUMEN_TOT_CLIENTE --UNIVERSO CLIENTES


SELECT * FROM FTORREN.RESUMEN_UTILIDAD --UTILIDAD <> 0 CLIENTES


SELECT * FROM FTORREN.RESUMEN_MOVIMIENTO --MOVIMIENTO DE SALDO ENTRE DIAS LOS ULTIMOS 6 MESES


SELECT * FROM FTORREN.RESUMEN_BALANCE --BALANCE MAYOR A 300USD
*/




DROP TABLE FTORREN.REPORTE;

CREATE TABLE FTORREN.REPORTE (
ID_REPORTE INT IDENTITY,
ANO_MES INT,
RUT INT,
DESC_BANCA VARCHAR(45),
IND_UTILIDAD VARCHAR(10),
IND_MOVIMIENTO VARCHAR(10),
IND_BALANCE VARCHAR(10)
)
CREATE UNIQUE
INDEX IDX_REPORTE
ON  FTORREN.REPORTE (ID_REPORTE,RUT)
WITH ALLOW_DUP_ROW;

CREATE INDEX IDX_ANOMES_RUT_RPT ON FTORREN.REPORTE (ANO_MES,RUT);

INSERT INTO FTORREN.REPORTE(
ANO_MES,
RUT,
DESC_BANCA,
IND_UTILIDAD,
IND_MOVIMIENTO,
IND_BALANCE
)
SELECT
A.ANO_MES,
A.RUT,
A.DESC_BANCA,
B.IND_UTILIDAD,
C.IND_MOVIMIENTO,
D.IND_BALANCE
FROM FTORREN.RESUMEN_TOT_CLIENTE A
LEFT JOIN FTORREN.RESUMEN_UTILIDAD B ON A.ANO_MES = B.ANO_MES AND A.RUT = B.RUT
LEFT JOIN FTORREN.RESUMEN_MOVIMIENTO C ON A.ANO_MES = C.ANO_MES AND A.RUT = C.RUT
LEFT JOIN FTORREN.RESUMEN_BALANCE D ON A.ANO_MES = D.ANO_MES AND A.RUT = D.RUT


SELECT * FROM FTORREN.REPORTE

WHERE IND_BALANCE IS NULL


SELECT ANO_MES, COUNT(*) FROM FTORREN.REPORTE
WHERE IND_UTILIDAD IS NOT NULL
AND IND_MOVIMIENTO IS NOT NULL
AND IND_BALANCE IS NOT NULL
GROUP BY ANO_MES

SELECT ANO_MES, COUNT(*) FROM FTORREN.REPORTE
WHERE IND_UTILIDAD IS NULL
AND IND_MOVIMIENTO IS NULL
AND IND_BALANCE IS NULL
GROUP BY ANO_MES

SELECT
ANO_MES,
RUT,
CASE
WHEN (IND_UTILIDAD  IS NULL
AND IND_MOVIMIENTO IS NULL
AND IND_BALANCE IS NULL) THEN 'NO ACTIVO'
WHEN (IND_UTILIDAD IS NOT NULL
OR IND_MOVIMIENTO IS NOT NULL
OR IND_BALANCE IS NOT NULL)
THEN 'ACTIVO'
END AS ESTADO
FROM FTORREN.REPORTE
WHERE ANO_MES IS NOT NULL
AND RUT IS NOT NULL



GROUP BY ANO_MES

SELECT ANO_MES, IND_UTILIDAD, COUNT(*) 
FROM FTORREN.REPORTE
WHERE IND_UTILIDAD IS NULL
GROUP BY ANO_MES, IND_UTILIDAD,IND_MOVIMIENTO,IND_BALANCE


SELECT
A.ANO_MES,
A.ESTADO,
COUNT(*)
FROM
(SELECT
ANO_MES,
RUT,
CASE
WHEN (IND_UTILIDAD  IS NULL
AND IND_MOVIMIENTO IS NULL
AND IND_BALANCE IS NULL) THEN 'NO ACTIVO'
WHEN (IND_UTILIDAD IS NOT NULL
OR IND_MOVIMIENTO IS NOT NULL
OR IND_BALANCE IS NOT NULL)
THEN 'ACTIVO'
END AS ESTADO
FROM FTORREN.REPORTE) A
GROUP BY
A.ANO_MES,
A.ESTADO


SELECT
A.ANO_MES,
COUNT(*)
FROM
(SELECT
ANO_MES,
RUT,
CASE
WHEN (IND_UTILIDAD  IS NULL
AND IND_MOVIMIENTO IS NULL
AND IND_BALANCE IS NULL) THEN 'NO ACTIVO'
WHEN (IND_UTILIDAD IS NOT NULL
OR IND_MOVIMIENTO IS NOT NULL
OR IND_BALANCE IS NOT NULL)
THEN 'ACTIVO'
END AS ESTADO
FROM FTORREN.REPORTE) A
GROUP BY
A.ANO_MES




SELECT
A.ANO_MES,
A.RUT,
A.DESC_BANCA,
B.FEC_APE AS APE_CCT,
C.FEC_APER AS APE_CVA
FROM FTORREN.REPORTE A
LEFT JOIN GESFOR.STOCK_CCT B
ON A.RUT = CONVERT(INT,B.RUT) AND A.ANO_MES = B.ANO_MES_DIA/100
LEFT JOIN GESFOR.STOCK_NOVA C
ON A.RUT = CONVERT(INT,B.RUT) AND A.ANO_MES = B.ANO_MES_DIA/100



SELECT COUNT(DISTINCT RUT) FROM GESFOR.STOCK_NOVA
WHERE ANO_MES_DIA/100 = 201606
OR ANO_MES_DIA/100 = 201706













