SELECT * FROM EDW_VW.EVENT_TRJ
WHERE EVENT_ACTIVITY_TYPE_CD IN (3,74,75,81) /* EVENTOS DE TARJETAS CREDITOS/DEBITOS */
AND EVENT_START_DT BETWEEN 1170701 AND 1170731/* RANGO DE FECHA DE EVENTOS */

SELECT
EVENT_CARD_ID
, CARD_ID
, EVENT_CARD_DT
, EVENT_CARD_TRX_TYPE_CD
, EVENT_CARD_POS_NUM
, EVENT_ATM_OPERATOR_NUM
, SBIF_BCO_TYPE_CD
, INTERNAL_BCO_TYPE_CD
, EVENT_CARD_AMT
FROM EDW_VW.EVENT_CARD_TRJ
WHERE EVENT_CARD_DT BETWEEN 1170701 AND 1170731

SELECT * FROM SBIF_BCO_TYPE

SELECT
COUNT(*)
FROM EDW_VW.EVENT_CARD_TRJ
WHERE EVENT_CARD_DT BETWEEN 1170502 AND 1170601
--AND SBIF_BCO_TYPE_CD = 3
AND INTERNAL_BCO_TYPE_CD = 21


SELECT
*
FROM EDW_VW.EVENT_CARD_TRJ
WHERE EVENT_CARD_DT BETWEEN 1170501 AND 1170531



SELECT
*
FROM EDW_VW.INTERNAL_BCO_TYPE
WHERE INTERNAL_BCO_TYPE_DESC LIKE '%INTERNACIONAL%'

SELECT
*
FROM EDW_VW.SBIF_BCO_TYPE
WHERE SBIF_BCO_TYPE_DESC LIKE '%INTERNACIONAL%'




CREATE TABLE EDW_TEMPUSU.EVENT_CARD_TRJ_SK AS
(
    SELECT * FROM EDW_VW.EVENT_CARD_TRJ
)
WITH NO DATA;

DROP TABLE EDW_TEMPUSU.EVENT_CARD_TRJ_SK

INSERT INTO EDW_TEMPUSU.EVENT_CARD_TRJ_SK
SELECT 
*
FROM EDW_VW.EVENT_CARD_TRJ
WHERE EVENT_CARD_DT BETWEEN 1170701 AND 1170731
AND SBIF_BCO_TYPE_CD = 3
AND INTERNAL_BCO_TYPE_CD = 21

SELECT * FROM EDW_TEMPUSU.EVENT_CARD_TRJ_SK


GRANT SELECT
     ON EDW_TEMPUSU.EVENT_CARD_TRJ_SK TO skataok;



SELECT
EVENT_CARD_DT,
EVENT_CARD_FILE_LOAD_DT,
EVENT_CARD_PROCESSING_DT
FROM EDW_TEMPUSU.EVENT_CARD_TRJ_TEST

SELECT COUNT(*) FROM EDW_TEMPUSU.EVENT_CARD_TRJ_TEST
WHERE EVENT_CARD_DT BETWEEN 1170501 AND 1170531


SELECT * FROM EDW_TEMPUSU.EVENT_CARD_TRJ_TEST

SELECT * FROM EDW_VW.EVENT_CARD_TRX_STATUS_TYPE

SELECT * FROM EDW_VW.EVENT_CARD_TRX_TYPE

SELECT * FROM EDW_VW.TRANSACTION_CODE_TYPE
