--COMISIONES PROVISIONES REDBANC ATM

--ELIMINA TABLAS
DROP TABLE EDW_TEMPUSU.PRV_BTX;
DROP TABLE EDW_TEMPUSU.PRV_BTX_EVENT_TRJ;
DROP TABLE EDW_TEMPUSU.PRV_BTX_EVENT_CARD_TRJ;
DROP TABLE EDW_TEMPUSU.PRV_BTX_RESUMEN;

--CREA TABLAS
CREATE TABLE EDW_TEMPUSU.PRV_BTX
(
ID INTEGER GENERATED ALWAYS AS IDENTITY
(START WITH 1 
 INCREMENT BY 1 
 MINVALUE -2147483647 
 MAXVALUE 2147483647 
 NO CYCLE)
, FCH_EVENTO VARCHAR(15)
, RUT VARCHAR(15)
, VRT VARCHAR(1)
, NRO_TARJETA VARCHAR(15)
, COD_TRX NUMBER(15)
, DESC_TRX VARCHAR(40)
, NRO_POS VARCHAR(9)
, NRO_TERMINAL VARCHAR(15)
, COD_BCO_SBIF NUMBER(15)
, DESC_BCO_SBIF VARCHAR(30)
, COD_BCO_INTERNAL NUMBER(15)
, DESC_BCO_INTERNAL VARCHAR(40)
, MONTO NUMBER(15)
)
PRIMARY INDEX (NRO_TARJETA,COD_TRX);

CREATE TABLE EDW_TEMPUSU.PRV_BTX_EVENT_TRJ
(
 ID INTEGER GENERATED ALWAYS AS IDENTITY
(START WITH 1 
 INCREMENT BY 1 
 MINVALUE -2147483647 
 MAXVALUE 2147483647 
 NO CYCLE)
, EVENT_ID NUMBER(15)
, EVENT_START_DT VARCHAR(15)
)
PRIMARY INDEX (EVENT_ID);

CREATE TABLE EDW_TEMPUSU.PRV_BTX_EVENT_CARD_TRJ
(
ID INTEGER GENERATED ALWAYS AS IDENTITY
(START WITH 1 
INCREMENT BY 1 
MINVALUE -2147483647 
MAXVALUE 2147483647 
NO CYCLE)
, EVENT_CARD_ID NUMBER(15,0)
, CARD_ID NUMBER(15,0)
, EVENT_CARD_DT NUMBER(15,0)
, EVENT_CARD_TRX_TYPE_CD VARCHAR(15)
, EVENT_CARD_POS_NUM VARCHAR(15)
, EVENT_ATM_OPERATOR_NUM NUMBER(15,0)
, SBIF_BCO_TYPE_CD NUMBER(15,0)
, INTERNAL_BCO_TYPE_CD NUMBER(15,0)
, EVENT_CARD_AMT NUMBER(15,0)
)
PRIMARY INDEX (EVENT_CARD_ID);

--CREA TABLA RESUMEN
CREATE TABLE EDW_TEMPUSU.PRV_BTX_RESUMEN
(
ID INTEGER GENERATED ALWAYS AS IDENTITY
(START WITH 1 
 INCREMENT BY 1 
 MINVALUE -2147483647 
 MAXVALUE 2147483647 
 NO CYCLE) 
,COD_BCO_SBIF NUMBER(15)
,DESC_BCO_SBIF VARCHAR(30)
,COD_BCO_INTERNAL NUMBER(15)
,DESC_BCO_INTERNAL VARCHAR(30)
,COD_TRX NUMBER(15)
,DESC_TRX VARCHAR(30)
,CANT_TRX NUMBER(15)
 )
PRIMARY INDEX (COD_BCO_SBIF,COD_TRX);

--CARGA PRIMERA TEMPORAL
INSERT INTO EDW_TEMPUSU.PRV_BTX_EVENT_TRJ (
  EVENT_ID
, EVENT_START_DT
)
SELECT EVENT_ID, EVENT_START_DT FROM EDW_VW.EVENT_TRJ
WHERE EVENT_ACTIVITY_TYPE_CD IN (3,74,75,81) /* EVENTOS DE TARJETAS CREDITOS/DEBITOS */
AND EVENT_START_DT BETWEEN 1170701 AND 1170731/* RANGO DE FECHA DE EVENTOS */
;

--CARGA SEGUNDA TEMPORAL
INSERT INTO EDW_TEMPUSU.PRV_BTX_EVENT_CARD_TRJ (
EVENT_CARD_ID
, CARD_ID
, EVENT_CARD_DT
, EVENT_CARD_TRX_TYPE_CD
, EVENT_CARD_POS_NUM
, EVENT_ATM_OPERATOR_NUM
, SBIF_BCO_TYPE_CD
, INTERNAL_BCO_TYPE_CD
, EVENT_CARD_AMT
)
SELECT
EVENT_CARD_ID
, CARD_ID
, EVENT_CARD_DT
, EVENT_CARD_TRX_TYPE_CD
, EVENT_CARD_POS_NUM
, EVENT_ATM_OPERATOR_NUM
, SBIF_BCO_TYPE_CD
, INTERNAL_BCO_TYPE_CD
, EVENT_CARD_AMT
FROM EDW_VW.EVENT_CARD_TRJ
WHERE EVENT_CARD_DT BETWEEN 1170701 AND 1170731
;

--CARGA DE DATOS
INSERT INTO EDW_TEMPUSU.PRV_BTX (
  FCH_EVENTO
, RUT
, VRT
, NRO_TARJETA
, COD_TRX
, DESC_TRX
, NRO_POS
, NRO_TERMINAL
, COD_BCO_SBIF
, DESC_BCO_SBIF
, COD_BCO_INTERNAL
, DESC_BCO_INTERNAL
, MONTO
)
SEL 
OREPLACE(CAST(A.EVENT_START_DT AS VARCHAR(10)),'-','') AS "FCH_EVENTO"
,(CASE
  WHEN EIH.EXT_IDENTIFICATION_TYPE_CD = '2' 
   THEN LPAD(SUBSTR(EIH.EXT_IDENTIFICATION_NUM,1,(CHARACTERS(EIH.EXT_IDENTIFICATION_NUM) -5)),8,'0')
    ELSE LPAD(SUBSTR(EIH.EXT_IDENTIFICATION_NUM,1,CHARACTERS(EIH.EXT_IDENTIFICATION_NUM)-1),8,'0')
     END)(VARCHAR(10)) AS RUT
,(SUBSTR(EIH.EXT_IDENTIFICATION_NUM,CHARACTER(EIH.EXT_IDENTIFICATION_NUM),1) (CHAR(1))) AS VRT    
,A.CARD_NUM AS "NRO_TARJETA"
,CAST(CAST(A.EVENT_CARD_TRX_TYPE_CD AS VARCHAR(15)) AS INTEGER) AS "COD_TRX"
,B.EVENT_CARD_TRX_TYPE_DESC AS "DESC_TRX"
,A.EVENT_CARD_POS_NUM AS "NRO_POS"
,A.EVENT_ATM_OPERATOR_NUM AS "NRO_TERMINAL"
,CAST(CAST(A.SBIF_BCO_TYPE_CD AS VARCHAR(15)) AS INTEGER) AS "COD_BCO_SBIF" 
,C.SBIF_BCO_TYPE_DESC AS "DESC_BCO_SBIF"
,CAST(CAST(D.INTERNAL_BCO_TYPE_CD AS VARCHAR(15)) AS INTEGER) AS "COD_BCO_INTERNAL" 
,D.INTERNAL_BCO_TYPE_DESC AS "DESC_BCO_INTERNAL"
,CAST(CAST(A.EVENT_CARD_AMT AS VARCHAR(15)) AS INTEGER) AS "MONTO"
FROM
(
SELECT
A.EVENT_START_DT
       ,B.EVENT_CARD_TRX_TYPE_CD
       ,B.EVENT_CARD_POS_NUM
       ,B.EVENT_ATM_OPERATOR_NUM
      ,B.SBIF_BCO_TYPE_CD
      ,B.INTERNAL_BCO_TYPE_CD
      ,B.EVENT_CARD_AMT
     ,B.CARD_ID
     ,CA.CARD_NUM
     ,AC.PARTY_ID 
FROM EDW_TEMPUSU.PRV_BTX_EVENT_TRJ A
LEFT JOIN  EDW_TEMPUSU.PRV_BTX_EVENT_CARD_TRJ B
ON   A.EVENT_ID = B.EVENT_CARD_ID
LEFT JOIN  EDW_VW.PARTY_CARD AC 
ON     B.CARD_ID = AC.CARD_ID 
LEFT JOIN  EDW_VW.CARD CA
ON B.CARD_ID = CA.CARD_ID
WHERE    AC.PARTY_CARD_ROLE_CD = 2 /* TITULAR TARJETA */
--AND AC.PARTY_CARD_REL_END_DT IS NULL /* QUE LA RELACION DE LA TARJETA Y EL CLIENTE ESTEN VIGENTE */
--AND B.SBIF_BCO_TYPE_CD = '7' /*BANCO A CONSULTAR*/
) A
LEFT JOIN EDW_VW.EXTERNAL_IDENTIFICATION_HIST EIH
ON A.PARTY_ID = EIH.PARTY_ID   
LEFT JOIN EDW_VW.EVENT_CARD_TRX_TYPE B
ON A.EVENT_CARD_TRX_TYPE_CD = B.EVENT_CARD_TRX_TYPE_CD
LEFT JOIN  EDW_VW.SBIF_BCO_TYPE C
ON  A.SBIF_BCO_TYPE_CD  = C.SBIF_BCO_TYPE_CD
LEFT JOIN  EDW_VW.INTERNAL_BCO_TYPE D
ON  A.INTERNAL_BCO_TYPE_CD  = D.INTERNAL_BCO_TYPE_CD
WHERE EXT_IDENTIFICATION_END_DT IS NULL /* RUT VIGENTE */
;

--CARGA TABLA RESUMEN
INSERT INTO EDW_TEMPUSU.PRV_BTX_RESUMEN (
 COD_BCO_SBIF
,DESC_BCO_SBIF
,COD_BCO_INTERNAL
,DESC_BCO_INTERNAL
,COD_TRX
,DESC_TRX
,CANT_TRX
)
SELECT 
COD_BCO_SBIF,
DESC_BCO_SBIF,
COD_BCO_INTERNAL,
DESC_BCO_INTERNAL,
COD_TRX,
DESC_TRX,
COUNT(*) as CANT_TRX
FROM EDW_TEMPUSU.PRV_BTX
--WHERE COD_BCO_SBIF IN (1,7,21,13,31,41,12,3,8)
GROUP BY COD_BCO_SBIF,DESC_BCO_SBIF,COD_BCO_INTERNAL,DESC_BCO_INTERNAL,COD_TRX,DESC_TRX
;

--PERMISOS A TABLA
GRANT SELECT
     ON EDW_TEMPUSU.PRV_BTX TO skataok;